/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LssWrapper */

#ifndef _Included_LssWrapper
#define _Included_LssWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LssWrapper
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_LssWrapper_initialize
  (JNIEnv *, jobject);

/*
 * Class:     LssWrapper
 * Method:    computeChisqC
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_LssWrapper_computeChisqC
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
